FROM python:3.8

COPY provider/main.py /root

RUN apt update && apt -y install libmariadb-dev-compat libmariadb-dev
RUN pip install flask flask_restx cryptography==38.0.1 pyOpenSSL==22.1.0 pycryptodomex requests mysqlclient pyjwt importlib-metadata

WORKDIR /root

CMD ["./python3 main.py"]
