ARG BASEIMAGE
ARG BASEIMAGE_TAG

FROM ${BASEIMAGE}:${BASEIMAGE_TAG}

# install go env
RUN apt update && apt install -y golang

RUN mkdir upload
COPY gramine_registry/main.go /upload/

COPY gramine_registry/build.sh /

RUN mkdir /root/code

# server
EXPOSE 8008
CMD ["go run ./upload/main.go"]
