FROM mysql:8.0

ENV MYSQL_USER user
ENV MYSQL_PASSWORD userpass

COPY db/01_create_db.sql /docker-entrypoint-initdb.d/01_create_db.sql
COPY db/02_create_data.sql /docker-entrypoint-initdb.d/02_create_data.sql
COPY db/03_permit.sql /docker-entrypoint-initdb.d/03_permit.sql

ENV MYSQL_ROOT_PASSWORD=root
